name: Auto Request Reviewer

on:
  pull_request:
    types: [opened]

jobs:
  reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Request Review from Copilot
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: ['github-copilot']
            });
