name: Auto Request Reviewer

on:
  pull_request:
    types: [opened]

jobs:
  reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Request Review from Copilot
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;

            await github.rest.pulls.requestReviewers({
              owner,
              repo,
              pull_number,
              reviewers: ['github-copilot'] // Change if needed
            });
